# Generated by Django 2.1.3 on 2018-11-20 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appears',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
                ('confirmed', models.BooleanField(default=False)),
                ('position', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('path', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('path', models.TextField()),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Corpus')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255)),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Dictionary')),
            ],
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Meaning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('posTag', models.CharField(max_length=200)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Entry')),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='example',
            name='meaning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Meaning'),
        ),
        migrations.AddField(
            model_name='document',
            name='meanings',
            field=models.ManyToManyField(through='api.Appears', to='api.Meaning'),
        ),
        migrations.AddField(
            model_name='document',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Period'),
        ),
        migrations.AddField(
            model_name='appears',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Document'),
        ),
        migrations.AddField(
            model_name='appears',
            name='meaning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Meaning'),
        ),
    ]
