# Generated by Django 2.1.2 on 2018-11-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181130_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='end',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='period',
            name='start',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
