# Generated by Django 2.1.2 on 2018-11-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20181130_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='path',
            field=models.TextField(max_length=255),
        ),
    ]
