# Generated by Django 2.1.2 on 2018-11-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181130_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='path',
        ),
        migrations.RemoveField(
            model_name='document',
            name='type',
        ),
        migrations.AddField(
            model_name='document',
            name='fileid',
            field=models.TextField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
