# Generated by Django 2.1.2 on 2018-12-03 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20181130_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appears',
            name='meaning',
        ),
        migrations.RemoveField(
            model_name='document',
            name='meanings',
        ),
        migrations.AddField(
            model_name='appears',
            name='entry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Entry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='birth_date',
            field=models.CharField(default='غير معروف', max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='death_date',
            field=models.CharField(default='غير معروف', max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='entries',
            field=models.ManyToManyField(through='api.Appears', to='api.Entry'),
        ),
    ]
