# Generated by Django 2.1.2 on 2018-12-06 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20181203_1615'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together={('term', 'dictionary')},
        ),
    ]
