# Generated by Django 2.1.2 on 2018-12-08 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20181208_1234'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='meaning',
            order_with_respect_to=None,
        ),
    ]
