# Generated by Django 2.1.2 on 2018-12-08 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20181208_1258'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meaning',
            unique_together=set(),
        ),
    ]
