# Generated by Django 2.1.2 on 2018-12-09 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20181208_1306'),
        ('api', '0007_auto_20181130_2338'),
    ]

    operations = [
    ]
