# Generated by Django 2.1.2 on 2018-12-11 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20181211_1056'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meaning',
            unique_together=set(),
        ),
        migrations.AlterOrderWithRespectTo(
            name='meaning',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='period',
            order_with_respect_to=None,
        ),
    ]
