# Generated by Django 2.1.2 on 2018-12-11 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20181209_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appears',
            name='entry',
        ),
        migrations.AddField(
            model_name='appears',
            name='meaning',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Meaning'),
        ),
        migrations.AddField(
            model_name='document',
            name='meanings',
            field=models.ManyToManyField(through='api.Appears', to='api.Meaning'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='document',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='period',
            order_with_respect_to=None,
        ),
        migrations.RemoveField(
            model_name='document',
            name='entries',
        ),
    ]
