# Generated by Django 2.1.2 on 2018-12-12 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20181211_1805'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appears',
            unique_together=set(),
        ),
    ]
