# Generated by Django 2.1.2 on 2018-12-15 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20181212_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordAppear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
                ('position', models.BigIntegerField()),
                ('word_position', models.BigIntegerField(default=-1)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Document')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Entry')),
            ],
        ),
        migrations.AlterModelOptions(
            name='meaning',
            options={'ordering': ('entry',)},
        ),
        migrations.AddField(
            model_name='document',
            name='entries',
            field=models.ManyToManyField(through='api.WordAppear', to='api.Entry'),
        ),
    ]
