# Generated by Django 2.1.2 on 2018-12-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20181215_1231'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='meaning',
            index=models.Index(fields=['entry'], name='api_meaning_entry_i_e51608_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['term'], name='api_entry_term_ef2310_idx'),
        ),
        migrations.AddIndex(
            model_name='appears',
            index=models.Index(fields=['meaning'], name='api_appears_meaning_790639_idx'),
        ),
        migrations.AddIndex(
            model_name='wordappear',
            index=models.Index(fields=['entry'], name='api_wordapp_entry_i_b2f9ee_idx'),
        ),
    ]
